name: Deploy Web App

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az group create --name bmsu-rg --location eastus2
          #use this command and paste the output to the AZURE_CREDENTIALS secret
          #az ad sp create-for-rbac --name "bmsu" --role contributor --scopes /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/bms-func-app-rg /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/bmsd-cont-app-rg /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/bmsu-rg --sdk-auth
          accountManagerFunctionKey=$(az functionapp keys list --resource-group "bms-func-app-rg" --name master-bms-accountmanager --query functionKeys.default | tr -d '"')
          signalRFunctionKey=$(az functionapp keys list --resource-group "bms-func-app-rg" --name master-bms-notificationmanager --query functionKeys.default | tr -d '"')
          accountManagerDaprBaseUrl=https://$(az containerapp show --resource-group "bmsd-cont-app-rg" --name accountmanager --query properties.configuration.ingress.fqdn | tr -d '"')
          signalRDaprNegotiateUrl=https://$(az containerapp show --resource-group "bmsd-cont-app-rg" --name notificationmanager --query properties.configuration.ingress.fqdn | tr -d '"')
          accountManagerFunctionBaseUrl=https://master-bms-accountmanager.azurewebsites.net/api/
          signalRFunctionNegotiateUrl=https://master-bms-notificationmanager.azurewebsites.net/api/
          
          az deployment group create --resource-group bmsu-rg --template-file ../Infra/main.bicep \
            --parameters branchName='master' \
            accountManagerFunctionKey=$accountManagerFunctionKey \
            signalRFunctionKey= $signalRFunctionKey\
            accountManagerDaprBaseUrl= $accountManagerDaprBaseUrl\
            signalRDaprNegotiateUrl= $signalRDaprNegotiateUrl\
            accountManagerFunctionBaseUrl=$accountManagerFunctionBaseUrl \
            signalRFunctionNegotiateUrl=$signalRFunctionNegotiateUrl
            
         
