name: Deploy Web App Code

on:
  workflow_dispatch:
  workflow_call:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NUGET_VERSION: '6.0.x'          
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
        
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
      
    - name: Build release version
      run: dotnet publish --configuration Release ./BankManagementSystemUI.sln
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: /subscriptions/4201e31c-f3e6-4c25-8e65-141498306589/resourceGroups/bmsu-rg/providers/Microsoft.Web/sites/bank-management-ui
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/BankManagementSystemUI/'
  
    # Azure logout 
    - name: logout
      run: |
        az logout