name: Deploy Web App Code

on:
  workflow_dispatch:
  workflow_call:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NUGET_VERSION: '7.0.x'          
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
     
    - name: Build release version
      run: |
       dotnet restore
       dotnet build --configuration Release
       dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
    
    - name: Zip deployment
      run: |
        cd '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        zip -r myapp.zip .
      
    - name: Zip Deploy
      run: az webapp deploy --resource-group bmsu-rg  --name bank-management-ui --src-path ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/myapp.zip --type zip
      
    # Azure logout 
    - name: logout
      run: |
        az logout