name: Deploy Web App Code

on:
  workflow_dispatch:
  workflow_call:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NUGET_VERSION: '6.0.x'          
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
     
    - name: 'Get App Name'
      id: getwebappname
      run: |
        a=$(az webapp list -g bmsu-rg --query '[].{Name:name}' -o tsv)
        echo "APP_NAME=$a" >> $GITHUB_ENV

    - name: Build release version
      run: |
       dotnet restore
       dotnet build --configuration Release
       dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
    
    - name: Zip deployment
      run: |
        cd '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        zip -r myapp.zip .
      
    - name: Zip Deploy
      run: az webapp deploy --resource-group bmsu-rg  --name bank-management-ui --src-path ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/myapp.zip --type zip
      
    #- name: 'Run Azure webapp deploy action using publish profile credentials'
    #  uses: azure/webapps-deploy@v2
    #  with: 
    #    app-name: bank-management-ui
    #    package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
  
    # Azure logout 
    - name: logout
      run: |
        az logout